[package]
name = "plmidi"
description = "Play MIDI files from the command line."
version = "0.9.0"
edition = "2018"
authors = [ "Taylan Gökkaya <insomnimus.dev@gmail.com>" ]
license = "MIT"
repository = "https://github.com/insomnimus/plmidi"
categories = ["command-line-utilities", "multimedia::audio", "multimedia::encoding"]
keywords = ["midi", "music", "smf"]
readme = "readme.md"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc" # avoids the need to download C dependencies
targets = []

[dependencies]
clap = "3.0.0-beta.4"
crossterm = "0.21.0"
log = "0.4.14"
midir = "0.7.0"
midly = "0.5.2"
nodi = { version = "0.12.0", features = ["hybrid-sleep"], optional = true }
simple_logger = { version = "1.13.0", features = ["stderr"], default-features = false }

[features]
default = ["nodi/midir"]
jack = ["nodi/jack"]
winrt = ["nodi/winrt"]
