[package]
name = "plmidi"
description = "Play MIDI files from the command line."
version = "0.7.0"
edition = "2018"
authors = [ "Taylan Gökkaya <insomnimus.dev@gmail.com>" ]
license = "MIT"
repository = "https://github.com/insomnimus/plmidi"
keywords = [ "midi", "music", "cli" ]

[dependencies]
clap = "3.0.0-beta.4"
log = "0.4.14"
midir = "0.7.0"
midly = "0.5.2"
nodi = { version = "0.9.2", features = [ "midir" ] }
simple_logger = { version = "1.13.0", features = ["stderr"], default-features = false }
