[package]
name = "plmidi"
description = "Play MIDI files from the command line."
version = "0.10.0"
edition = "2018"
authors = [ "Taylan Gökkaya <insomnimus.dev@gmail.com>" ]
license = "MIT"
repository = "https://github.com/insomnimus/plmidi"
categories = ["command-line-utilities", "multimedia::audio", "multimedia::encoding"]
keywords = ["midi", "music", "smf"]
readme = "readme.md"

[dependencies]
clap = { version = "3.1.18", features = ["cargo", "unicode", "wrap_help"] }
crossterm = "0.23.2"
log = "0.4.17"
midir = "0.8.0"
midly = "0.5.2"
nodi = { version = "0.15.2", features = ["hybrid-sleep"], optional = true }
simple_logger = { version = "2.1.0", features = ["stderr"], default-features = false }

[features]
default = ["nodi/midir"]
jack = ["nodi/jack"]
winrt = ["nodi/winrt"]
