{
  "name": "All",
  "on": [
    "push",
    "pull_request"
  ],
  "jobs": {
    "test": {
      "strategy": {
        "matrix": {
          "include": [
            {
              "os": "ubuntu-latest",
              "target": "x86_64-unknown-linux-gnu"
            },
            {
              "os": "macOS-11",
              "target": "x86_64-apple-darwin"
            },
            {
              "os": "windows-latest",
              "target": "x86_64-pc-windows-msvc"
            }
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Setup | Install Dependencies",
          "if": "matrix.os == 'ubuntu-latest'",
          "env": {
            "DEBIAN_FRONTEND": "noninteractive"
          },
          "run": "sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential pkg-config libasound2-dev"
        },
        {
          "name": "Setup | Rust",
          "if": "matrix.os != 'ubuntu-latest'",
          "uses": "actions-rs/toolchain@v1.0.7",
          "with": {
            "toolchain": "stable",
            "override": true,
            "profile": "minimal",
            "target": "${{ matrix.target }}"
          }
        },
        {
          "name": "Setup | Rust",
          "if": "matrix.os == 'ubuntu-latest'",
          "uses": "actions-rs/toolchain@v1.0.7",
          "with": {
            "toolchain": "stable",
            "override": true,
            "profile": "minimal",
            "components": "clippy",
            "target": "${{ matrix.target }}"
          }
        },
        {
          "name": "Check | Clippy",
          "if": "matrix.os == 'ubuntu-latest'",
          "uses": "actions-rs/cargo@v1.0.3",
          "with": {
            "command": "clippy",
            "args": "--locked --target ${{ matrix.target }}"
          }
        },
        {
          "name": "Check | Tests",
          "uses": "actions-rs/cargo@v1.0.3",
          "with": {
            "command": "test",
            "args": "--locked --target ${{ matrix.target }}"
          }
        }
      ]
    },
    "build": {
      "name": "Build Release Binaries",
      "needs": "test",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "continue-on-error": true,
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "include": [
            {
              "os": "ubuntu-latest",
              "name": "plmidi-linux-x64.tar.gz",
              "target": "x86_64-unknown-linux-gnu"
            },
            {
              "os": "macOS-11",
              "name": "plmidi-osx-x64.tar.gz",
              "target": "x86_64-apple-darwin"
            },
            {
              "os": "windows-latest",
              "name": "plmidi-windows-x64.zip",
              "target": "x86_64-pc-windows-msvc"
            },
            {
              "os": "ubuntu-latest",
              "target": "aarch64-unknown-linux-gnu",
              "name": "plmidi-linux-aarch64.tar.gz"
            },
            {
              "os": "windows-latest",
              "target": "i686-pc-windows-msvc",
              "name": "plmidi-windows-x86.zip"
            },
            {
              "os": "ubuntu-latest",
              "target": "i686-unknown-linux-gnu",
              "name": "plmidi-linux-x86.tar.gz"
            },
            {
              "os": "macos-11",
              "target": "aarch64-apple-darwin",
              "name": "plmidi-osx-aarch64.tar.gz"
            }
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Setup | Cache Cargo",
          "uses": "actions/cache@v2.1.6",
          "with": {
            "path": "~/.cargo/registry\n~/.cargo/git\n",
            "key": "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
          }
        },
        {
          "name": "Setup | Install Dependencies",
          "if": "matrix.os == 'ubuntu-latest'",
          "env": {
            "DEBIAN_FRONTEND": "noninteractive"
          },
          "run": "sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential pkg-config libasound2-dev"
        },
        {
          "name": "Setup | Rust",
          "uses": "actions-rs/toolchain@v1.0.7",
          "with": {
            "toolchain": "stable",
            "override": true,
            "profile": "minimal",
            "target": "${{ matrix.target }}"
          }
        },
        {
          "name": "Build | Build",
          "uses": "actions-rs/cargo@v1.0.3",
          "with": {
            "command": "build",
            "args": "--release --locked --target ${{ matrix.target }}"
          }
        },
        {
          "name": "PostBuild | Prepare",
          "if": "matrix.os != 'windows-latest'",
          "run": "cd target/${{ matrix.target }}/release\nstrip plmidi || true\ntar czvf ../../../${{ matrix.name }} plmidi\ncd -"
        },
        {
          "if": "matrix.os == 'windows-latest'",
          "name": "PostBuild | Prepare",
          "run": "cd target/${{ matrix.target }}/release\n7z a ../../../${{ matrix.name }} plmidi.exe\ncd -"
        },
        {
          "name": "Deploy | Upload Artifacts",
          "uses": "actions/upload-artifact@v2",
          "with": {
            "name": "${{ matrix.name }}",
            "path": "${{ matrix.name }}"
          }
        }
      ]
    },
    "release": {
      "name": "Create GitHub Release",
      "needs": "build",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Setup | Checkout",
          "uses": "actions/checkout@v2.3.4",
          "with": {
            "fetch-depth": 0
          }
        },
        {
          "name": "Setup | go",
          "uses": "actions/setup-go@v2",
          "with": {
            "go-version": "^1.15.7"
          }
        },
        {
          "name": "Setup | Artifacts",
          "uses": "actions/download-artifact@v2"
        },
        {
          "name": "Setup | Release notes",
          "run": "GO111MODULE=on go install github.com/git-chglog/git-chglog/cmd/git-chglog@0.9.1\ngit-chglog -c .github/chglog/release.yml $(git describe --tags) > RELEASE.md\n"
        },
        {
          "name": "Deploy | Publish",
          "uses": "softprops/action-gh-release@v1",
          "with": {
            "files": "plmidi-*/plmidi-*",
            "body_path": "RELEASE.md"
          }
        }
      ]
    }
  }
}
